### ISSUE TITLE
PHP - specific readme info

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/laravel-starter-buttercms#1]

**Comment by janondracek1** [comment]
@ViolanteCodes 
Hello, may I ask what exactly should I include?
Is there anything speficing you are referring to? 

As far as I am aware, I removed most of unrelated readme info and introduced more relevant information to PHP.

**Comment by ViolanteCodes** [comment]
@janondracek1 you can ignore this for now - I opened this as a note to myself to look at if the docs/readme for php will need to be updated as a result of the other issue.

**Comment by ViolanteCodes** [comment]
Updated readme and pushed changes to master
