### ISSUE TITLE
Slider missing header

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/laravel-starter-buttercms#4]
Should look like this: [https://share.getcloudapp.com/KouA9bEA](https://share.getcloudapp.com/KouA9bEA)

But looks like this: [https://share.getcloudapp.com/bLuKlnOv](https://share.getcloudapp.com/bLuKlnOv)

**Comment by janondracek1** [comment]
@ViolanteCodes 
Fixed, as can be seen in PR #6
