### ISSUE TITLE
Trailing slash missing from search route

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/laravel-starter-buttercms#5]
To search for query "Butter", for example, URL returned by search is "`http://localhost:8000/blog/search/?q=butter`" (missing trailing slash). Adding trailing slash to route in URL bar, for example, "http://localhost:8000/blog/search/?q=butter/", shows page with search term `"butter/`". We'd like for the route to have/require a trailing slash, same as the other routes. Is this doable? Thanks!

**Comment by janondracek1** [comment]
@ViolanteCodes 
It is doable, but
 - It is a terrible practice
 - It would require implementing/tweaking middleware and would be too difficuilt to implement, for what purpose it serves
 
Trailing slashes before query parameters make sense, but after them? I do not think I've ever seen that being implemented.

**Comment by ViolanteCodes** [comment]
@janondracek1 Yep, you're right, I'm closing out this issue. After consulting my notes, we had to temporarily add it to a checklist as a workaround and it was not pulled from checklist. Sorry about that, and thank you for taking the time to explain.
